### PR TITLE
Fixed memory leaks/usage

### PR DESCRIPTION
**Pull request by TsundereBug**

### CODE REVIEW

**Comment by ArsenArsen** [comment]
The compiler does this for you.

**Comment by TsundereBug** [comment]
The compiler turns it into StringBuffers for you. StringBuilders are lots faster.

**Comment by ArsenArsen** [comment]
No. It doesn't. It picks the appropriate one. [Reference](https://stackoverflow.com/questions/26048633/java-compiler-replacing-stringbuilder-with-concatenation#26048687)

**Comment by TsundereBug** [comment]
This started when? And why is it appropriate to use concatenation, even when all of my Lint tools say not to?

**Pull request merged**
